---
title: Danielle Navarro"
author: Danielle Navarro
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['custom_resume.css', 'styles.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---


```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)
library(tidyverse)
library(glue)

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- FALSE

# Holds all the links that were inserted for placement at the end
links <- c()

source('parsing_functions.R') # Functions for building sections from CSV data
source('common_variables.R')  # Small variables for non-csv data such as intro text

# First let's get the data, filtering to only the items tagged as
# Resume items
position_data <- read_csv('positions.csv') %>% 
  filter(in_resume) %>% 
  mutate(
    # Build some custom sections by collapsing others
    section = case_when(
      section %in% c('research_positions', 'industry_positions') ~ 'positions', 
      section %in% c('data_science_writings', 'by_me_press') ~ 'writings',
      TRUE ~ section
    )
  ) 

```


Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------



- <i class="fa fa-envelope"></i> djnavarro@protonmail.com
- <i class="fa fa-twitter"></i> [twitter.com/djnavarro](git@github.com:djnavarro/cv.git)
- <i class="fa fa-github"></i> [github.com/djnavarro](https://github.com/djnavarro)
- <i class="fa fa-graduation-cap"></i> [djnavarro.link/scholar](https://djnavarro.link/scholar)
- <i class="fa fa-link"></i> [djnavarro.net](https://djnavarro.net)



Language Skills {#skills}
--------------------------------------------------------------------------------


```{r}
build_skill_bars(skills)
```



Open Source Contributions {#open-source}
--------------------------------------------------------------------------------

All projects available at `github.com/nstrayer/<name>`


- `shinysense`: R package to use sensor data in Shiny apps
- `tuftesque`: Hugo theme (behind LiveFreeOrDichotomize.com)
- `slid3r`: D3 add-on for fully svg slider inputs



Main
================================================================================

Danielle Navarro {#title}
--------------------------------------------------------------------------------

```{r}
cat(sanitize_links(intro_text))
```




Selected Positions {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('positions')
```

Selected Writing {data-icon=newspaper}
--------------------------------------------------------------------------------


```{r}
position_data %>% print_section('writings')
```


